version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn sayit.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/sayit
      - static_volume:/home/sayit/web/static
    expose:
      - 8000
    env_file:
      - ./.env/prod.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/sayit/web/static
    ports:
      - 1337:80
    depends_on:
      - web
      
volumes:
  static_volume:
