# Generated by Django 3.1.7 on 2021-08-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_auto_20210804_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_accessed_at',
        ),
    ]
