# Generated by Django 3.1.7 on 2021-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0004_auto_20210805_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
