# Generated by Django 3.1.7 on 2021-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0005_auto_20210809_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
